services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev.backend
    ports:
      - "5000:5000"
    environment:
      - APP_NAME='CropDoc'
      - SECRET_KEY='secretkey'
      - FLASK_APP=manage.py
      - FLASK_ENV=development
      - LOGGING_LEVEL=DEBUG
    volumes:
      - ./CropDoc:/CropDoc
    command: flask run --host 0.0.0.0 --port 5000 --reload

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000
    depends_on:
      - backend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    command: npm run dev