# Use an official Python runtime as the base image
FROM python:3.10.11-slim

# Set the working directory in the container
WORKDIR /CropDoc

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copy the requirements file into the container
COPY CropDoc/requirements.txt .

# Install PyTorch separately
RUN pip install --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Install Flask development server for hot reloading
RUN pip install --no-cache-dir flask[async]

# Expose the port the app runs on
EXPOSE 5000

# Command to run the application with hot reloading
CMD ["python", "manage.py", "runserver", "--reload"]