services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - APP_NAME='CropDoc'
      - SECRET_KEY='secretkey'
      - FLASK_APP=manage.py
      - FLASK_ENV=development
      - LOGGING_LEVEL=DEBUG
    volumes:
      - ./CropDoc:/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app