services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev.backend
    
    ports:
      - "5000:5000"
    environment:
      - APP_NAME='CropDoc'
      - SECRET_KEY='secretkey'
      - FLASK_APP=manage.py
      - FLASK_ENV=development
      - LOGGING_LEVEL=DEBUG
      - ALLOWED_ORIGINS=http://localhost:3000,http://frontend:3000
    volumes:
      - ./CropDoc:/CropDoc
    networks:
      - app-network
    command: python manage.py runserver --reload

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    depends_on:
      - backend
    networks:
      - app-network
    command: npm run dev

networks:
  app-network:
    name: cosc320-groupd_app-network
    external: true
    driver: bridge