pipeline:
  python_file:
  dataset_dir: data/datasets/CCMT Dataset-Augmented
  output_dir: data/output
model:
  name: ResNet50
  type: Classification
  version: 1.0
  architecture:
    - type: ResNet
  training:
    epochs: 1
    val_split: 0.8
    batch_size: 48
    num_workers: 4 #  Number of works, more info here: https://pytorch.org/docs/stable/data.html#multi-process-data-loading
    lr_scheduler:
      step_size: 3
      gamma: 0.1
    loss_function: # List of loss functions can be found here: https://pytorch.org/docs/stable/nn.html#loss-functions  
      type: CrossEntropyLoss
  data:
    reduce: 0.05 # Percentage of data from dataset to be used for training (0-1), can be lowered to speed up training to test development faster
    transformers: # List of data transformers can be found here: https://pytorch.org/vision/0.9/transforms.html
      train:
        - type: RandomResizedCrop
          size: 224
        - type: RandomHorizontalFlip
        - type: ColorJitter
          brightness: 0.2
          contrast: 0.2
          saturation: 0.2
          hue: 0.1
        - type: RandomRotation
          degrees: 20
        - type: RandomAffine
          degrees: 0
          translate: [0.1, 0.1]
        - type: ToTensor
        - type: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      val:
        - type: Resize
          size: 256
        - type: CenterCrop
          size: 224
        - type: ToTensor
        - type: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      test:
        - type: Resize
          size: 256
        - type: CenterCrop
          size: 224
        - type: ToTensor
        - type: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]   
  evaluation:
    metrics:
      - accuracy
      - precision
      - recall
    batch_size: 64
