# Example configuration file for a crop disease classification model

model:
  name: CropDiseaseClassifier
  type: CNN  # Type of model (e.g., CNN, SVM, etc.)
  architecture: 
    - type: Conv2D
      filters: 32
      kernel_size: 3
      activation: relu
    - type: MaxPooling2D
      pool_size: 2
    - type: Flatten
    - type: Dense
      units: 64
      activation: relu
    - type: Dense
      units: 10  # Number of disease classes
      activation: softmax

training:
  epochs: 50
  batch_size: 32
  learning_rate: 0.001

data:
  transformers:
    train:
      - type: RandomResizedCrop
        size: 224
      - type: RandomHorizontalFlip
      - type: ColorJitter
        brightness: 0.2
        contrast: 0.2
        saturation: 0.2
        hue: 0.1
      - type: RandomRotation
        degrees: 20
      - type: RandomAffine
        degrees: 0
        translate: [0.1, 0.1]
      - type: ToTensor
      - type: Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    val:
      - type: Resize
        size: 256
      - type: CenterCrop
        size: 224
      - type: ToTensor
      - type: Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    test:
      - type: Resize
        size: 256
      - type: CenterCrop
        size: 224
      - type: ToTensor
      - type: Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
      


evaluation:
  metrics:
    - accuracy
    - precision
    - recall
  batch_size: 64

